package main

import (
	"bytes"
	"flag"
	"fmt"
	"golang.org/x/tools/go/packages"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/seyyedaghaei/ifacegen/internal/generator"
	"github.com/seyyedaghaei/ifacegen/internal/loader"
)

func main() {
	matchFlag := flag.String("match", "", "Comma-separated glob patterns to match struct names (e.g. *Service)")
	outputFlag := flag.String("output", "iface_gen.go", "Name of the generated interface file")
	nameFlag := flag.String("name", "I{}", "Naming pattern for interfaces. '{}' replaced by struct name")
	helpFlag := flag.Bool("help", false, "Show usage information")

	flag.Usage = func() {
		_, _ = fmt.Fprintf(flag.CommandLine.Output(), `Usage:
  ifacegen [flags] <package pattern>

Example:
  ifacegen -match=*Service,*Repository ./...

Flags:
`)
		flag.PrintDefaults()
	}

	flag.Parse()

	if *helpFlag {
		flag.Usage()
		os.Exit(0)
	}

	if flag.NArg() == 0 {
		flag.Usage()
		os.Exit(1)
	}

	pkgs := loader.LoadPackages(flag.Args()...)

	if len(pkgs) == 0 {
		log.Fatalln("Warning: no packages matched the given pattern(s)")
	}

	matches := splitMatches(*matchFlag)

	sem := make(chan struct{}, runtime.NumCPU())
	var wg sync.WaitGroup

	for _, pkg := range pkgs {
		wg.Add(1)
		go func(pkg *packages.Package) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			code, err := generator.Generate(pkg, *nameFlag, matches)
			if err != nil {
				log.Printf("Error generating for package %s: %v", pkg.PkgPath, err)
				return
			}

			outFile := filepath.Join(filepath.Dir(pkg.GoFiles[0]), *outputFlag)

			if code == nil {
				iface, _ := os.ReadFile(outFile)
				if strings.HasPrefix(string(iface), "// Code generated by ifacegen. DO NOT EDIT.") {
					if err := os.Remove(outFile); err != nil && !os.IsNotExist(err) {
						log.Printf("Failed to remove %s: %v", outFile, err)
					}
				}
				return
			}
			if wrote, err := writeIfChanged(outFile, code); err != nil {
				log.Printf("Error writing file %s: %v", outFile, err)
				return
			} else if wrote {
				log.Printf("Generated interfaces for package %s", pkg.PkgPath)
			}
		}(pkg)
	}
	wg.Wait()
}

func splitMatches(s string) []string {
	var res []string
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part != "" {
			res = append(res, part)
		}
	}
	return res
}

func writeIfChanged(path string, content []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return false, nil
	}
	return true, os.WriteFile(path, content, 0644)
}
