// Code generated by ifacegen. DO NOT EDIT.
package consumer

import (
	"github.com/seyyedaghaei/ifacegen/testdata/alias/pkgone"
	shared2 "github.com/seyyedaghaei/ifacegen/testdata/alias/pkgtwo"
)

type IAliasService interface {
	Combine() (shared.Thing, shared2.Thing)
}
