// Code generated by ifacegen. DO NOT EDIT.
package matchskip

type IGenerated interface {
	DoSomething() error
}

type IMethodSkipService interface {
	Visible() error
}

type IUserService interface {
	CreateUser(name string) error
	GetUser(id int) (*User, error)
}

