package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/spf13/pflag"
	"golang.org/x/tools/go/packages"

	"github.com/seyyedaghaei/ifacegen/internal/cli"
	"github.com/seyyedaghaei/ifacegen/internal/generator"
	"github.com/seyyedaghaei/ifacegen/internal/loader"
)

var version = "dev"

func main() {
	matchFlag := pflag.StringP("match", "m", "", "Comma-separated glob patterns to match struct names (e.g. *Service)")
	outputFlag := pflag.StringP("output", "o", "iface_gen.go", "Name of the generated interface file")
	nameFlag := pflag.StringP("name", "n", "I{}", "Naming pattern for interfaces. '{}' replaced by struct name")
	versionFlag := pflag.BoolP("version", "v", false, "Show version information")
	helpFlag := pflag.BoolP("help", "h", false, "Show usage information")
	dryRunFlag := pflag.BoolP("dry-run", "d", false, "Show what would be generated without writing files")
	verboseFlag := pflag.BoolP("verbose", "V", false, "Enable verbose output")
	watchFlag := pflag.BoolP("watch", "w", false, "Watch for file changes and regenerate automatically")
	progressFlag := pflag.BoolP("progress", "p", true, "Show progress indicators (default: true)")
	interactiveFlag := pflag.BoolP("interactive", "i", false, "Start interactive configuration mode")

	pflag.Usage = func() {
		_, _ = fmt.Fprintf(pflag.CommandLine.Output(), `Usage:
  ifacegen [flags] <package pattern>

Example:
  ifacegen --match=*Service,*Repository ./...
  ifacegen --dry-run --match=*Service ./...
  ifacegen --watch --match=*Service ./...
  ifacegen --interactive

Flags:
`)
		pflag.PrintDefaults()
		_, _ = fmt.Fprintf(pflag.CommandLine.Output(), "\nVersion: %s\n", version)
	}

	pflag.Parse()

	if *helpFlag {
		pflag.Usage()
		os.Exit(0)
	}

	if *versionFlag {
		fmt.Printf("ifacegen version %s\n", version)
		os.Exit(0)
	}

	if *verboseFlag {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
	}

	if *interactiveFlag {
		config, err := cli.RunInteractive()
		if err != nil {
			if err.Error() == "user cancelled" {
				os.Exit(0)
			}
			log.Fatalf("Interactive mode error: %v", err)
		}

		fmt.Printf("\n🚀 Generated command: %s\n\n", config.GenerateCommand())

		if config.Watch {
			runWatchMode([]string{"./..."}, strings.Join(config.MatchPatterns, ","), config.OutputFile, config.NamePattern, config.DryRun, config.Verbose, config.Progress)
		} else {
			runGeneration([]string{"./..."}, strings.Join(config.MatchPatterns, ","), config.OutputFile, config.NamePattern, config.DryRun, config.Verbose, config.Progress)
		}
		return
	}

	patterns := pflag.Args()
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}

	if *watchFlag {
		runWatchMode(patterns, *matchFlag, *outputFlag, *nameFlag, *dryRunFlag, *verboseFlag, *progressFlag)
		return
	}

	runGeneration(patterns, *matchFlag, *outputFlag, *nameFlag, *dryRunFlag, *verboseFlag, *progressFlag)
}

func runGeneration(patterns []string, matchFlag, outputFlag, nameFlag string, dryRun, verbose, progress bool) {
	if verbose {
		log.Printf("Loading packages from patterns: %v", patterns)
	}

	pkgs := loader.LoadPackages(patterns...)

	if len(pkgs) == 0 {
		log.Fatalln("Warning: no packages matched the given pattern(s)")
	}

	if verbose {
		log.Printf("Found %d packages to process", len(pkgs))
	}

	matches := splitMatches(matchFlag)

	if dryRun {
		fmt.Println("🔍 DRY RUN MODE - No files will be written")
		fmt.Println(strings.Repeat("=", 50))
	}

	maxWorkers := runtime.NumCPU()
	if len(pkgs) < maxWorkers {
		maxWorkers = len(pkgs)
	}
	sem := make(chan struct{}, maxWorkers)
	var wg sync.WaitGroup

	processedCount := 0
	var mu sync.Mutex

	for _, pkg := range pkgs {
		wg.Add(1)
		go func(pkg *packages.Package) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			code, err := generator.Generate(pkg, nameFlag, matches)
			if err != nil {
				log.Printf("Error generating for package %s: %v", pkg.PkgPath, err)
				return
			}

			outFile := filepath.Join(filepath.Dir(pkg.GoFiles[0]), outputFlag)

			if code == nil {
				if !dryRun {
					iface, err := os.ReadFile(outFile)
					if err == nil && strings.HasPrefix(string(iface), "// Code generated by ifacegen. DO NOT EDIT.") {
						if err := os.Remove(outFile); err != nil && !os.IsNotExist(err) {
							log.Printf("Failed to remove %s: %v", outFile, err)
						}
					}
				}
				if verbose {
					log.Printf("No interfaces to generate for package %s", pkg.PkgPath)
				}
				return
			}

			if dryRun {
				mu.Lock()
				processedCount++
				if progress {
					fmt.Printf("📦 [%d/%d] Package: %s\n", processedCount, len(pkgs), pkg.PkgPath)

					diffResult := generator.GenerateDiff(outFile, code)
					if diffResult.HasDiff {
						fmt.Print(generator.FormatDiffResult(diffResult))
					} else {
						fmt.Printf("   ✅ No changes needed\n")
					}
					fmt.Println("   " + strings.Repeat("-", 40))
				}
				mu.Unlock()
				return
			}

			if wrote, err := writeIfChanged(outFile, code); err != nil {
				log.Printf("Error writing file %s: %v", outFile, err)
				return
			} else if wrote {
				mu.Lock()
				processedCount++
				if progress {
					fmt.Printf("✅ [%d/%d] Generated interfaces for package %s\n", processedCount, len(pkgs), pkg.PkgPath)
				} else {
					log.Printf("Generated interfaces for package %s", pkg.PkgPath)
				}
				mu.Unlock()
			} else if verbose {
				log.Printf("No changes needed for package %s", pkg.PkgPath)
			}
		}(pkg)
	}
	wg.Wait()

	if dryRun {
		fmt.Println(strings.Repeat("=", 50))
		fmt.Printf("🎯 Dry run completed. Would process %d packages.\n", len(pkgs))
	} else if progress {
		fmt.Printf("\n🎉 Generation completed! Processed %d packages.\n", len(pkgs))
	}
}

func runWatchMode(patterns []string, matchFlag, outputFlag, nameFlag string, dryRun, verbose, progress bool) {
	if verbose {
		log.Printf("Starting watch mode for patterns: %v", patterns)
	}

	fmt.Println("👀 WATCH MODE - Press Ctrl+C to stop")
	fmt.Println("Watching for changes in:", strings.Join(patterns, ", "))

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	lastRun := time.Now()

	for range ticker.C {
		hasChanges, newest := goFilesChangedSince(patterns, lastRun)
		if hasChanges {
			fmt.Println("\n🔄 Changes detected, regenerating...")
		} else if verbose {
			log.Printf("No changes detected; skipping regeneration")
			continue
		} else {
			continue
		}

		runGeneration(patterns, matchFlag, outputFlag, nameFlag, dryRun, verbose, progress)
		lastRun = newest
		fmt.Println("👀 Watching for changes...")
	}
}

func goFilesChangedSince(patterns []string, since time.Time) (bool, time.Time) {
	shouldScanCwd := false
	for _, p := range patterns {
		if p == "./..." || p == "." || p == "./" || p == "..." {
			shouldScanCwd = true
			break
		}
	}

	if !shouldScanCwd {
		return true, time.Now()
	}

	newest := since
	changed := false

	_ = filepath.WalkDir(".", func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "vendor":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		info, err := d.Info()
		if err != nil {
			return nil
		}
		mt := info.ModTime()
		if mt.After(since) {
			changed = true
			if mt.After(newest) {
				newest = mt
			}
		}
		return nil
	})

	return changed, newest
}

func splitMatches(s string) []string {
	var res []string
	for _, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part != "" {
			res = append(res, part)
		}
	}
	return res
}

func writeIfChanged(path string, content []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return false, nil
	}
	return true, os.WriteFile(path, content, 0644)
}
