package generator

import (
	"bytes"
	"fmt"
	"os"
	"strings"
)

// DiffResult represents the result of a diff operation
type DiffResult struct {
	File    string
	Action  string // "create", "update", "delete", "no-change"
	OldSize int
	NewSize int
	Preview string
	HasDiff bool
}

// GenerateDiff creates a diff preview for the given file and content
func GenerateDiff(filePath string, newContent []byte) DiffResult {
	result := DiffResult{
		File:    filePath,
		NewSize: len(newContent),
	}

	// Check if file exists
	existingContent, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			result.Action = "create"
			result.HasDiff = true
			result.Preview = generateCreatePreview(newContent)
		} else {
			result.Action = "error"
			result.Preview = fmt.Sprintf("Error reading file: %v", err)
		}
		return result
	}

	result.OldSize = len(existingContent)

	// Check if content is the same
	if bytes.Equal(existingContent, newContent) {
		result.Action = "no-change"
		result.HasDiff = false
		return result
	}

	// Check if it's a generated file
	if strings.HasPrefix(string(existingContent), "// Code generated by ifacegen. DO NOT EDIT.") {
		result.Action = "update"
		result.HasDiff = true
		result.Preview = generateUpdatePreview(existingContent, newContent)
	} else {
		result.Action = "overwrite"
		result.HasDiff = true
		result.Preview = generateOverwritePreview(newContent)
	}

	return result
}

func generateCreatePreview(content []byte) string {
	lines := strings.Split(string(content), "\n")
	if len(lines) > 20 {
		lines = lines[:20]
		lines = append(lines, "...")
	}

	var preview strings.Builder
	preview.WriteString("📄 New file will be created:\n")
	for _, line := range lines {
		_, _ = fmt.Fprintf(&preview, "+ %s\n", line)
	}
	return preview.String()
}

func generateUpdatePreview(oldContent, newContent []byte) string {
	newLines := strings.Split(string(newContent), "\n")

	var preview strings.Builder
	preview.WriteString("📝 Generated file will be updated:\n")

	// Show first few lines of new content
	previewLines := newLines
	if len(previewLines) > 15 {
		previewLines = previewLines[:15]
		previewLines = append(previewLines, "...")
	}

	for _, line := range previewLines {
		_, _ = fmt.Fprintf(&preview, "  %s\n", line)
	}

	_, _ = fmt.Fprintf(
		&preview,
		"\n📊 Size change: %d → %d bytes (%+d)\n",
		len(oldContent),
		len(newContent),
		len(newContent)-len(oldContent),
	)

	return preview.String()
}

func generateOverwritePreview(content []byte) string {
	lines := strings.Split(string(content), "\n")
	if len(lines) > 15 {
		lines = lines[:15]
		lines = append(lines, "...")
	}

	var preview strings.Builder
	preview.WriteString("⚠️  Existing file will be overwritten:\n")
	for _, line := range lines {
		_, _ = fmt.Fprintf(&preview, "  %s\n", line)
	}
	return preview.String()
}

// FormatDiffResult formats a diff result for display
func FormatDiffResult(result DiffResult) string {
	if !result.HasDiff {
		return ""
	}

	var output strings.Builder
	_, _ = fmt.Fprintf(&output, "📦 %s\n", result.File)

	switch result.Action {
	case "create":
		output.WriteString("   ➕ Will create new file\n")
	case "update":
		output.WriteString("   🔄 Will update generated file\n")
	case "overwrite":
		output.WriteString("   ⚠️  Will overwrite existing file\n")
	case "delete":
		output.WriteString("   🗑️  Will delete file\n")
	}

	if result.Preview != "" {
		output.WriteString("   " + strings.ReplaceAll(result.Preview, "\n", "\n   "))
	}

	output.WriteString("\n")
	return output.String()
}
