package generator

import (
	"bytes"
	"golang.org/x/tools/go/packages"
	"text/template"
)

const tmpl = `// Code generated by ifacegen. DO NOT EDIT.
package {{.Package}}
{{- if .Imports}}
import (
{{- range .Imports }}
	{{.}}
{{- end }}
)
{{- end }}
{{range .Interfaces}}
{{- if .Comment}}
	{{.Comment}}{{end}}
type {{.Name}} interface {
{{- range .Methods}}
{{- if .Comment}}
	{{.Comment}}{{end}}
	{{.Signature}}
{{- end}}
}
{{end}}`

var ifaceTmpl = template.Must(template.New("iface").Parse(tmpl))

type interfaceInfo struct {
	Name    string
	Comment string
	Methods []methodInfo
}

type methodInfo struct {
	Comment   string
	Signature string
}

type packageData struct {
	pkg        *packages.Package
	pkgImps    map[string]string
	pkgCounter map[string]int

	Package    string
	Imports    []string
	Interfaces []interfaceInfo
}

func Generate(pkg *packages.Package, name string, matches []string) ([]byte, error) {
	data := &packageData{
		pkg:        pkg,
		pkgImps:    make(map[string]string),
		pkgCounter: make(map[string]int),
		Package:    pkg.Name,
	}

	if err := data.processPackage(name); err != nil {
		return nil, err
	}

	return data.render()
}

func (d *packageData) processPackage(name string) error {
	return nil
}

func (d *packageData) render() ([]byte, error) {
	if len(d.Interfaces) == 0 {
		return nil, nil
	}

	var buf bytes.Buffer

	if err := ifaceTmpl.Execute(&buf, d); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
